import 'package:azkar/core/app_constant/app_strings.dart';
import 'package:azkar/core/app_constant/azkar_constant.dart';
import 'package:azkar/presentation/widget/zekr_item.dart';
import 'package:azkar/presentation/widget/top_title.dart';
import 'package:flutter/material.dart';

class AzkarMorningScreen extends StatelessWidget {
  const AzkarMorningScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ListView(padding: EdgeInsets.zero,
          physics: const BouncingScrollPhysics(),
          children: [
            Center(child: buildITopTitle(context,title: AppString.azkarMorning)),

           buildZekrItem(context,
             title: AzkarString.ayatElkorsi,
              subTitle:AzkarString.ayatElkorsiSub,
              number: AzkarNumbers.ayatElkorsi,),
            buildZekrItem(context,
              title: AzkarString.alekhlas,
              subTitle:AzkarString.alekhlasSub,
              number: AzkarNumbers.alekhlas,),
            buildZekrItem(context,
              title: AzkarString.alfalaq,
              subTitle:AzkarString.alfalaqSub,
              number: AzkarNumbers.alfalaq,),
            buildZekrItem(context,
              title: AzkarString.alnas,
              subTitle:AzkarString.alnasSub,
              number: AzkarNumbers.alnas,),
            buildZekrItem(context,
              title: AzkarString.asbhna,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.asbhna,),
            buildZekrItem(context,
              title: AzkarString.allahom,
              subTitle:AzkarString.allahomSub,
              number: AzkarNumbers.allahom,),
            buildZekrItem(context,
              title: AzkarString.radito,
              subTitle:AzkarString.raditoSub,
              number: AzkarNumbers.radito,),
            buildZekrItem(context,
              title: AzkarString.allahoma,
              subTitle:AzkarString.allahomaSub,
              number: AzkarNumbers.allahoma,),
            buildZekrItem(context,
              title: AzkarString.allahomma,
              subTitle:AzkarString.allahommaSub,
              number: AzkarNumbers.allahomma,),
            buildZekrItem(context,
              title: AzkarString.hasbya,
              subTitle:AzkarString.hasbyaSub,
              number: AzkarNumbers.hasbya,),
            buildZekrItem(context,
              title: AzkarString.bassmala,
              subTitle:AzkarString.bassmalaSub,
              number: AzkarNumbers.bassmala,),
            buildZekrItem(context,
              title: AzkarString.allohmabek,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.allohmabek,),
            buildZekrItem(context,
              title: AzkarString.asbahna1,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.asbahna1,),
            buildZekrItem(context,
              title: AzkarString.sobhana,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.sobhana,),
            buildZekrItem(context,
              title: AzkarString.allhomma,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.allhomma,),
            buildZekrItem(context,
              title: AzkarString.a3ooz,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.a3ooz,),
            buildZekrItem(context,
              title: AzkarString.asalok,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.asalok,),
            buildZekrItem(context,
              title: AzkarString.ya7y,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.ya7y,),
            buildZekrItem(context,
              title: AzkarString.asb7na,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.asb7na,),
            buildZekrItem(context,
              title: AzkarString.a3alm,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.a3alm,),
            buildZekrItem(context,
              title: AzkarString.a3oozo,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.a3oozo,),
            buildZekrItem(context,
              title: AzkarString.sally,
              subTitle:AzkarString.sallySub,
              number: AzkarNumbers.sally,),
            buildZekrItem(context,
              title: AzkarString.n3ooz,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.n3ooz,),
            buildZekrItem(context,
              title: AzkarString.asta5fer,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.asta5fer,),
            buildZekrItem(context,
              title: AzkarString.yarab,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.yarab,),
            buildZekrItem(context,
              title: AzkarString.asalok,
              subTitle:AzkarString.Null,
              number: AzkarNumbers.asalok,),
            buildZekrItem(context,
              title: AzkarString.allhomAnt,
              subTitle:AzkarString.allhomAntSub,
              number: AzkarNumbers.allhomAnt,),
            buildZekrItem(context,
              title: AzkarString.laElh,
              subTitle:AzkarString.laElhSub,
              number: AzkarNumbers.laElh,),
            buildZekrItem(context,
              title: AzkarString.sob7ana,
              subTitle:AzkarString.sob7anaSub,
              number: AzkarNumbers.sob7ana,),
            buildZekrItem(context,
              title: AzkarString.ast5fer,
              subTitle:AzkarString.ast5ferSub,
              number: AzkarNumbers.ast5fer,),

          ],
        ),
    );
  }

}
